First version of the `tls-requirer` operator
canonical/tls-certificates-requirer-operator pull request #1
Opened 2023-05-14 22:06 UTC by gruyaume

## Overview
First version of the `tls-requirer` operator. Charm that requests X.509 certificates using the `tls-certificates` interface.

It uses the user-provided `subject` configuration to generate a certificate signing request
(CSR) that will be inserted into its unit relation data as soon as the `tls-certificates` relation
is created. In return, the certificate provider should use this CSR, generate a certificate, 
and provide it back into their application relation data.

This charm is useful when developing and testing certificate providers.

## Usage

Deploy the charm and relate it to a certificate provider:

```bash
juju deploy tls-requirer-operator
juju relate tls-requirer-operator <TLS Certificates Provider>
```

Access the generated certificate:

```bash
juju run tls-requirer-operator/leader get-certificate
```

## Limitations

This charm doesn't scale up.

## Relations

- `tls-certificates`: Used for charms that require/provide TLS certificates.

2023-05-15 21:14 UTC, ghislainbourgeois requested changes

2023-05-15 21:14 UTC, ghislainbourgeois commented on .github/workflows/publish-charm.yaml
> +          path: /root/snap/charmcraft/common/cache/charmcraft/log/*.log
I think this is not required

2023-05-15 21:14 UTC, ghislainbourgeois commented on config.yaml
> +    default: ubuntu.com
I don't think we want to use `ubuntu.com` here.
```suggestion
    default: tls-requirer-operator
```

2023-05-15 21:14 UTC, ghislainbourgeois commented on src/charm.py
> +            return False
```suggestion
            return bool(self.model.get_relation(relation_name))
```

2023-05-15 21:14 UTC, ghislainbourgeois commented on src/charm.py
> +    return "".join(secrets.choice(chars) for _ in range(12))
```suggestion
    return secrets.token_bytes(12)
```

2023-05-16 13:19 UTC, gruyaume commented on .github/workflows/publish-charm.yaml
> +          path: /root/snap/charmcraft/common/cache/charmcraft/log/*.log
Removed

2023-05-16 19:26 UTC, ghislainbourgeois approved these changes

2023-05-16 21:35 UTC, merged